mod chrome;
mod detail;
mod draw;
mod history;
mod intake;
pub(crate) mod intake_paper;
mod main_window;
mod media;
mod orig_view;
mod preview_doc;
mod scroll;
pub(crate) mod search_field;
mod selectable;
mod settings;
pub(crate) mod source_editor;
mod source_panel;
mod text_buffer;
mod theme;
mod widgets;
mod window_drag;

pub use main_window::MainWindow;
